<a href="https://colab.research.google.com/github/matteol1/DeepLearning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

In [4]:
# Basic Tensor Operations

In [22]:
array_a = np.array([[1,2],[2,1]])
array_b = np.array([[0,3],[4,1]])
array_c = np.array([[1,3,7]])

In [23]:
array_a

array([[1, 2],
       [2, 1]])

In [24]:
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)
tensor_c = torch.tensor(array_c)

In [25]:
print(tensor_a)

tensor([[1, 2],
        [2, 1]])


###Basic Tensor Math Operations Addition

In [30]:
#Addition

torch.add(tensor_a, tensor_b)

tensor([[1, 5],
        [6, 2]])

In [31]:
# Shorthand notation - operator overload

tensor_a + tensor_b

tensor([[1, 5],
        [6, 2]])

In [29]:
# Class method operation

tensor_a.add(tensor_b)

tensor([[1, 5],
        [6, 2]])

### Subtraction

In [32]:
tensor_b - tensor_a

tensor([[-1,  1],
        [ 2,  0]])

In [33]:
torch.sub(tensor_b, tensor_a)

tensor([[-1,  1],
        [ 2,  0]])

In [34]:
tensor_b.sub(tensor_a)

tensor([[-1,  1],
        [ 2,  0]])

Multiplication and Division also work in the same way performing elemnt-wiser arithmetic operations.

Still, same arithmetic works for exponential and modulus


In [35]:
torch.pow(tensor_a, tensor_b)

tensor([[ 1,  8],
        [16,  1]])

In [42]:
tensor_b % tensor_a

tensor([[0, 1],
        [0, 0]])

In [46]:
tensor_a / tensor_b

# Automatically converts to float

tensor([[   inf, 0.6667],
        [0.5000, 1.0000]])

If the dimensions of the tensors are different we get an error.

In [43]:
tensor_a + tensor_c

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [44]:
tensor_a ^ tensor_b

# What is this?
# Not the same as the power above.

tensor([[1, 1],
        [6, 0]])

We can reassign directly when performing the arithmetic.

In [47]:
tensor_a + tensor_b

tensor([[1, 5],
        [6, 2]])

In [50]:
tensor_a.add_(tensor_b)

tensor([[1, 5],
        [6, 2]])

In [51]:
tensor_a

tensor([[1, 5],
        [6, 2]])

In [52]:
# Not very pretty, but might be useful here and there

## Reshaping

In [56]:
tensor_d = tensor_a.reshape(-1)

In [55]:
print(tensor_a)

tensor([[1, 5],
        [6, 2]])


In [57]:
print(tensor_d)

tensor([1, 5, 6, 2])


In [ ]:
#Reshaped into a single row / column

In [61]:
tensor_c.reshape(3,1)

tensor([[1],
        [3],
        [7]])

In [62]:
tensor_c.reshape(1,3)

tensor([[1, 3, 7]])

In [66]:
tensor_a.view((1,4))

tensor([[1, 5, 6, 2]])